### ISSUE TITLE
Show Mic/ Speakers Muted

### ISSUE THREAD

**Issue by Badetuch** [LeonMarcel-HD/StreamDeck-TeamSpeak5#11]
First up, I really appreciate the plugin and it works great for me.

The idea is to change the icon on the stream deck to a muted microphone/speaker when being toggled so.
The Discord Plugin has the exact same feature.

**Comment by Gamer92000** [comment]
That is the expected behavior. Does this not work for you?
It should look like that:
https://github.com/LeonMarcel-HD/StreamDeck-TeamSpeak5/blob/main/src/assets/mute/mic_off.svg

**Comment by Badetuch** [comment]
weird, the plugin works fine but the animation doesnt work for me
but its not too bad since i've switched back to ts3 anyways.

**Comment by LeonMarcel-HD** [comment]
Otherwise you can manually set custom Icons for the Plugin
