### ISSUE TITLE
Pluging doesn't work for TS 5 (version 5.0.0-beta77 build 1702382332)

### ISSUE THREAD

**Issue by gloin01** [LeonMarcel-HD/StreamDeck-TeamSpeak5#13]
I bought myself a Stream Deck MK.2 and want to use it to control TeamSpeak 5.
However this Plugin sadly doesn't currently seem to work, even though it shows "TeamSpeak Connected!".

I could accept the request of the Plugin in the "Remote Apps" setting in TS5, however it didn't work.
I tried resetting the permission in the TS5 settings by removing it from the list. Then I could accept it again, but then it completely disappeared and I haven't seen it on there since.
When pressing any buttons on the stream deck it just doesn't seem to do anything.

- TS 5 version 5.0.0-beta77 build 1702382332
- Stream Deck 6.8.1 (21263) (with Stream Deck MK.2)
- Windows 10 Pro 22H2 19045.5131

Edit: I just found out that the communication and connection does seem to be working, as I can see the icon change when I mute myself. However, pressing the button still doesn't do anything.

**Comment by LeonMarcel-HD** [comment]
As per the Setup instructions:

After the connection is established, you need to bind each Stream Deck Button to a TeamSpeak Keybinding.

(Similar to what you do with a regular Key. The Plugin just sends virtual Keys)

So set up your Buttons on the Stream Deck, select the corresponding function you want the Button mapped to.

For example, you place the Mute Action on your Stream Deck, then you need to select Choose on the Mute Binding in TeamSpeak and press the Button on the Stream Deck. You need to repeat this for every other Key, as TeamSpeak currently does not offer a way to set up the Bindings automatically!

---

So the finished setup for the Key Bindings should look something like this:

![image](https://github.com/user-attachments/assets/f4f135c4-1cd8-4a00-a850-e0bc4b77d34f)

**Comment by FrankyDE** [comment]
Oh thanks a lot!
I was searching all the time for the binding on the Streamdeck not realizing that it is a setting on Teamspeak.
Thanks a lot and sorry - now it seems so obvious, but i was just not finding / realizing that before.
I took a screenshot, that would have pointed me to the right direction. Maybe that helps others now.

🙏 Greetings from Hamburg
Yours Frank

![Image](https://github.com/user-attachments/assets/df28d3be-3ffd-4d6f-bc4a-2e858cd39d51)
