### ISSUE TITLE
[BUG] | Remote App request every time TeamSpeak gets restarted

### ISSUE THREAD

**Issue by MorphinMG** [LeonMarcel-HD/StreamDeck-TeamSpeak5#7]
**Describe the bug**
Every time i Restart TS5 i have to renew the permission of the Stream Deck plugin. 

**To Reproduce**
1. Restart Teamspeak 5
2. Click on any Streamdeck Key from the TS5 Plugin
3. The Persmission popup from Teamspeak will show up.

**Expected behavior**
Would be nice, if the Persmission could be permanent.

**Additional context**
 - Operating System:  WIN10 Home
 - Stream Deck Version:  6.3.0.18948
 - Plugin Version: newest
 - TeamSpeak Version: newest

**Comment by LeonMarcel-HD** [comment]
Try removing the Remote App Request in the settings. Settings -> Remote Apps -> Right click the App, and click Remove App.

I was able to reproduce it at first and this seemed to fix the problem.

**Comment by MorphinMG** [comment]
I Removed it. Then it Automatic Muted me and set "AFK"
Restarted TS, Gave the Permission, Restarted again, need to give Permissions again. Dont Seem to work for me.

**Comment by LeonMarcel-HD** [comment]
Okay, the first one is known to me and cannot be fixed, as TeamSpeak behaves weirdly with these hotkeys.

Then open regedit, go to this key `@HKEY_CURRENT_USER\Software\Elgato Systems GmbH\StreamDeck` add a new DWORD entry named `html_remote_debugging_enabled` and set the value to 1.

This is just for debugging and maybe trough that TeamSpeak receives the API Key. 

_So you can be sure that this is an official debug tool, here is the Documentation from Elgato:_ https://docs.elgato.com/sdk/plugins/getting-started#windows-debugging

**Comment by LeonMarcel-HD** [comment]
It seems to be as simple as just restarting the Stream Deck software, to get the right API Key sent to TeamSpeak
